### ISSUE TITLE
建议在readme中加入一项说明

### ISSUE THREAD

**Issue by zyp997** [snail007/goproxy-ss-plugin-android#1]
@snail007 
说明：
在使用插件连接时，很多国产手机会显示”未知插件“，出现无法连接的情况。
需要在手机管家->权限管理->自启动管理中将ShadowsocksGoProxyPlugn设置为允许启动。

还有就是有个问题：
为何在电脑端使用起来网速和延迟正常，而在手机端这两个方面要差很多。

**Comment by snail007** [comment]
多谢反馈，后续加上。另外速度应该和你网络情况和手机性能有关，还有就是dns。

**Comment by zyp997** [comment]
好的，谢谢。
