### ISSUE TITLE
 where put the key and crt files to in Android phone?

### ISSUE THREAD

**Issue by wimmerX** [snail007/goproxy-ss-plugin-android#5]
HI🐱,how to use this the goproxy-ss-plugin-android  in an encrypted form.Like `proxy sps -S http -T tls -P 127.0.0.1:8080 -t tcp -p :18080 -C proxy.crt -K proxy.key -h aes-192-cfb -j pass`.I dont konw where put the key and crt files to in my Android phone.🧐

**Comment by snail007** [comment]
put it in application's data files folder and then using absolute path with argument.

**Comment by wimmerX** [comment]
As you say,I put the file proxy.crt and proxy.key into the absolute path(/data/data) in my phone .Then, I use following command line like `-S socks -T tls -P  -C /data/data/proxy.crt -K /data/data/proxy.key -h aes-192-cfb -j pass` with **goproxy-ss-plugin-android,**
the ip and port number have been specified in the ss client.
As a result, what drives me crazy is that it reported an error :
> libss-local exits too fast(exit code:255)

Is there a problem  in my configuration or arguments?

**Comment by snail007** [comment]
wrong path ，application has no permission to  access it.

**Comment by wimmerX** [comment]
I tried putting in the path `/data/data/com.github.shadowsocks.plugin.goproxy` and `/data/data/com.github.shadowsocks` still reporting the same error, I intend to give up this method.
